name: Manual Run Script

on:
  workflow_dispatch: # 允许你在 Actions 界面手动点击按钮运行

jobs:
  execute:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Tools
        run: |
          pip install requests playwright
          playwright install chromium

      - name: Run
        run: python main.py
